"""change_inquiry_price_columns_to_double

Revision ID: 00e68c821776
Revises: 220b7855a8b0
Create Date: 2026-03-31 14:16:07.669802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e68c821776'
down_revision: Union[str, Sequence[str], None] = '220b7855a8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquiry_items', 'line_item_price',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('inquiry_items', 'estimated_price',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
    op.create_index(op.f('ix_order_milestones_order_id'), 'order_milestones', ['order_id'], unique=False)
    op.create_index('ix_orders_inquiry_id', 'orders', ['inquiry_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_declarations_milestone_id'), 'payment_declarations', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_payment_declarations_order_id'), 'payment_declarations', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_declarations_user_id'), 'payment_declarations', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_milestone_id'), 'transactions', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_milestone_id'), table_name='transactions')
    op.drop_index(op.f('ix_payment_declarations_user_id'), table_name='payment_declarations')
    op.drop_index(op.f('ix_payment_declarations_order_id'), table_name='payment_declarations')
    op.drop_index(op.f('ix_payment_declarations_milestone_id'), table_name='payment_declarations')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_inquiry_id', table_name='orders')
    op.drop_index(op.f('ix_order_milestones_order_id'), table_name='order_milestones')
    op.alter_column('inquiry_items', 'estimated_price',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inquiry_items', 'line_item_price',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
