"""add_invoice_fields

Revision ID: 1c3900872797
Revises: 8d1171b9cdf5
Create Date: 2026-03-20 20:01:24.804187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3900872797'
down_revision: Union[str, Sequence[str], None] = '8d1171b9cdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax_amount', sa.Double(), nullable=True))
    op.add_column('orders', sa.Column('shipping_amount', sa.Double(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Double(), nullable=True))
    op.add_column('quote_versions', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('quote_versions', sa.Column('shipping_amount', sa.Float(), nullable=True))
    op.add_column('quote_versions', sa.Column('discount_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_versions', 'discount_amount')
    op.drop_column('quote_versions', 'shipping_amount')
    op.drop_column('quote_versions', 'tax_amount')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'tax_amount')
    # ### end Alembic commands ###
