"""add_split_type_due_date_address

Revision ID: 2063dce8ad8c
Revises: 601d875a85dc
Create Date: 2026-04-01 22:22:33.261558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2063dce8ad8c'
down_revision: Union[str, Sequence[str], None] = '601d875a85dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_milestones', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('split_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('orders', 'split_type')
    op.drop_column('order_milestones', 'due_date')
    # ### end Alembic commands ###
