"""Add milestone split_type and custom request flag

Revision ID: 2aeff7da8cce
Revises: 2063dce8ad8c
Create Date: 2026-04-01 23:31:09.872886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aeff7da8cce'
down_revision: Union[str, Sequence[str], None] = '2063dce8ad8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_milestones', sa.Column('split_type', sa.String(), server_default='HALF', nullable=False))
    op.drop_constraint(op.f('uix_order_milestone_index'), 'order_milestones', type_='unique')
    op.create_unique_constraint('uix_order_milestone_split_index', 'order_milestones', ['order_id', 'split_type', 'order_index'])
    op.add_column('orders', sa.Column('is_custom_milestone_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_custom_milestone_requested')
    op.drop_constraint('uix_order_milestone_split_index', 'order_milestones', type_='unique')
    op.create_unique_constraint(op.f('uix_order_milestone_index'), 'order_milestones', ['order_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.drop_column('order_milestones', 'split_type')
    # ### end Alembic commands ###
