"""add admin_notes to inquiry_groups

Revision ID: 2e647941266c
Revises: 54f2d08390ab
Create Date: 2026-03-22 00:38:30.238600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e647941266c'
down_revision: Union[str, Sequence[str], None] = '54f2d08390ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_groups', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('orders_payment_gateway_order_id_key'), 'orders', type_='unique')
    op.create_foreign_key(None, 'reviews', 'sub_services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'order_milestones', ['milestone_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('users', 'email_bounced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'wishlists', 'sub_services', ['sub_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.alter_column('users', 'email_bounced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_unique_constraint(op.f('orders_payment_gateway_order_id_key'), 'orders', ['payment_gateway_order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inquiry_groups', 'admin_notes')
    # ### end Alembic commands ###
