"""Add inventory models

Revision ID: 448ab8540058
Revises: eb354b3ed850
Create Date: 2026-04-18 20:56:30.398854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '448ab8540058'
down_revision: Union[str, Sequence[str], None] = 'eb354b3ed850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_definitions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('PAPER', 'INK', 'BOARD', 'LAMINATE', 'GLUE', 'CONSUMABLE', name='materialtype'), nullable=False),
    sa.Column('uom', sa.Enum('SHEET', 'KG', 'SQ_INCH', 'PCS', name='unittype'), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_batches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('owner_type', sa.Enum('FACTORY', 'CUSTOMER', name='ownertype'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('initial_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('batch_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(owner_type = 'FACTORY') OR (owner_type = 'CUSTOMER' AND customer_id IS NOT NULL)", name='check_customer_ownership_integrity'),
    sa.CheckConstraint('current_quantity >= 0', name='check_current_quantity_not_negative'),
    sa.CheckConstraint('initial_quantity >= 0', name='check_initial_quantity_not_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='check_unit_cost_not_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index(op.f('ix_inventory_batches_customer_id'), 'inventory_batches', ['customer_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_material_id'), 'inventory_batches', ['material_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.Enum('RECEIVE', 'CONSUMPTION', 'WASTAGE', 'RETURN_TO_CUSTOMER', 'MANUAL_RECONCILIATION', name='transactiontype'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost_impact', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('total_cost_impact >= 0', name='check_total_cost_impact_not_negative'),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_ledger_batch_id'), 'inventory_ledger', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_job_id'), 'inventory_ledger', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_ledger_job_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_batch_id'), table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_inventory_batches_material_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_customer_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_table('material_definitions')
    # ### end Alembic commands ###
