"""add features and specifications to sub_products and sub_services

Revision ID: 601d875a85dc
Revises: 00e68c821776
Create Date: 2026-03-31 17:38:18.885722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601d875a85dc'
down_revision: Union[str, Sequence[str], None] = '00e68c821776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_products', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sub_products', sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sub_services', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sub_services', sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_services', 'specifications')
    op.drop_column('sub_services', 'features')
    op.drop_column('sub_products', 'specifications')
    op.drop_column('sub_products', 'features')
    # ### end Alembic commands ###
