"""add is_offline to orders and inquiries

Revision ID: 66ecea6a9d6c
Revises: 2e647941266c
Create Date: 2026-03-22 15:18:59.162488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ecea6a9d6c'
down_revision: Union[str, Sequence[str], None] = '2e647941266c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_groups', sa.Column('is_offline', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('is_offline', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_offline')
    op.drop_column('inquiry_groups', 'is_offline')
    # ### end Alembic commands ###
