"""Add SEOConfig table

Revision ID: 7dd2dc50c086
Revises: 2aeff7da8cce
Create Date: 2026-04-07 22:53:26.658196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd2dc50c086'
down_revision: Union[str, Sequence[str], None] = '2aeff7da8cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(), nullable=True),
    sa.Column('og_title', sa.String(), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_configs_id'), 'seo_configs', ['id'], unique=False)
    op.create_index(op.f('ix_seo_configs_path'), 'seo_configs', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_configs_path'), table_name='seo_configs')
    op.drop_index(op.f('ix_seo_configs_id'), table_name='seo_configs')
    op.drop_table('seo_configs')
    # ### end Alembic commands ###
