"""add_invoice_data_column

Revision ID: 8465a306364a
Revises: e090be59963a
Create Date: 2026-04-10 04:16:46.221972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8465a306364a'
down_revision: Union[str, Sequence[str], None] = 'e090be59963a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invoice_data')
    # ### end Alembic commands ###
