"""add_address_and_order_snapshots

Revision ID: d5d0392fa40c
Revises: 8465a306364a
Create Date: 2026-04-16 20:01:17.911072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d0392fa40c'
down_revision: Union[str, Sequence[str], None] = '8465a306364a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address_type', sa.Enum('BILLING', 'SHIPPING', name='addresstype'), nullable=False),
    sa.Column('address_line_1', sa.String(length=200), nullable=False),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('customer_billing_snapshot', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('customer_shipping_snapshot', sa.JSON(), nullable=True))
    op.add_column('sub_products', sa.Column('gst_rate', sa.Double(), nullable=True))
    op.alter_column('sub_products', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sub_products', 'sgst_rate')
    op.drop_column('sub_products', 'cgst_rate')
    op.drop_column('sub_products', 'cess_rate')
    op.drop_column('sub_products', 'igst_rate')
    op.add_column('sub_services', sa.Column('type', sa.String(), nullable=True))
    op.add_column('sub_services', sa.Column('gst_rate', sa.Float(), nullable=True))
    op.drop_column('sub_services', 'sgst_rate')
    op.drop_column('sub_services', 'cgst_rate')
    op.drop_column('sub_services', 'cess_rate')
    op.drop_column('sub_services', 'igst_rate')
    op.add_column('users', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'gstin')
    op.add_column('sub_services', sa.Column('igst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_services', sa.Column('cess_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_services', sa.Column('cgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_services', sa.Column('sgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sub_services', 'gst_rate')
    op.drop_column('sub_services', 'type')
    op.add_column('sub_products', sa.Column('igst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_products', sa.Column('cess_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_products', sa.Column('cgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sub_products', sa.Column('sgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('sub_products', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sub_products', 'gst_rate')
    op.drop_column('orders', 'customer_shipping_snapshot')
    op.drop_column('orders', 'customer_billing_snapshot')
    op.drop_table('addresses')
    # ### end Alembic commands ###
