"""add_hsn_gst_fields

Revision ID: e82286e5f970
Revises: 978d3fbe20ae
Create Date: 2026-03-21 03:11:43.961285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82286e5f970'
down_revision: Union[str, Sequence[str], None] = '978d3fbe20ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('payment_gateway_order_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_payment_gateway_order_id'), 'orders', ['payment_gateway_order_id'], unique=True)
    op.add_column('sub_products', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('sub_products', sa.Column('cgst_rate', sa.Double(), nullable=True))
    op.add_column('sub_products', sa.Column('sgst_rate', sa.Double(), nullable=True))
    op.add_column('sub_services', sa.Column('hsn_code', sa.String(), nullable=True))
    op.add_column('sub_services', sa.Column('cgst_rate', sa.Float(), nullable=True))
    op.add_column('sub_services', sa.Column('sgst_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_services', 'sgst_rate')
    op.drop_column('sub_services', 'cgst_rate')
    op.drop_column('sub_services', 'hsn_code')
    op.drop_column('sub_products', 'sgst_rate')
    op.drop_column('sub_products', 'cgst_rate')
    op.drop_column('sub_products', 'hsn_code')
    op.drop_index(op.f('ix_orders_payment_gateway_order_id'), table_name='orders')
    op.drop_column('orders', 'payment_gateway_order_id')
    # ### end Alembic commands ###
